server:
  port: 9704
spring:
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://c1:5555/geo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: spider
    password: dB&x(oNt1lR)
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

tongcheng:
  letter: https://www.ly.com/hotelapi/gethotelcitysbyletter

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml